AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
