require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.6

Rails:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/SymbolArray:
  Enabled: false
