default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hajs-api_development

test:
  <<: *default
  database: hajs-api_test

production:
  <<: *default
  database: hajsapp_production
  username: hajsapp
  password: <%= ENV['HAJSAPP_DB_PASSWORD'] %>
