default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hajs-api_development

test:
  <<: *default
  database: hajs-api_test

production:
  <<: *default
  database: hajsapp_production
  username: hajsapp
  password: <%= ENV['HAJSAPP_DB_PASSWORD'] %>
